
FROM nginx

LABEL version="1.0.0" description="Container Nginx e NodeJS" maintainer="Antoniel Lima<antoniel@desenroladev.com.br>"

WORKDIR /app

COPY ./start.dev.sh /start.sh

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g nodemon

COPY ./default.conf /etc/nginx/conf.d/default.conf

ENV PORT=3000

VOLUME /app

EXPOSE 80

CMD [ "/start.sh" ]
